# -*- coding: utf-8 -*-
"""Image Processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MrghAdLW47azjxvjLqoI6IiKYAQdCtGU
"""

from google.colab.patches import cv2_imshow
import cv2

img = cv2.imread('/content/drive/MyDrive/Internship_2023/car.jpg')
height, width = img.shape[0:2]

# print(type(img))
# cv2_imshow(img)
# cv2.waitKey(0)

###                           Cropping the Image  

# startrow = int(height*.15)
# startcol = int(width*.15)
# endrow = int(height*.85)
# endcol = int(width*.85)

# croppedimage = img[startrow:endrow, startcol:endcol]
# cv2_imshow(croppedimage)
# cv2.waitKey(0)

###                           Rotating the Image

# height, width = img.shape[0:2]
# img.shape[0:2]

# rotationMatrix = cv2.getRotationMatrix2D((width/2, height/2), 90, .5)
# rotatedImage = cv2.warpAffine(img, rotationMatrix, (width, height))
# cv2_imshow(rotatedImage)

###                           Resizing the Image

resizedimage = cv2.resize(img, (0, 0), fx = 0.35, fy = 0.35)
cv2_imshow(resizedimage)

contrastedimage = 0.2 *